import { ContentItem } from '@/lib/types';

// ci_001 — HIGH PERFORMING: TikTok-first authority video, all 6 platforms published
// ci_002 — FAILED: Product promo, failed on TikTok + Facebook
// ci_003 — DRAFT ONLY: Early-stage idea, no metrics, 3 platforms
// ci_004 — APPROVED/SCHEDULED: Educational carousel across 4 platforms
// ci_005 — MIXED STATE: Approved on LinkedIn, blocked on YouTube

export const CONTENT_ITEMS_PART1: ContentItem[] = [
  // ─── ci_001 ─── HIGH PERFORMING ────────────────────────────────────────────
  {
    id: 'ci_001',
    title: 'AI is replacing junior developers — here\'s what actually happens',
    type: 'video',
    status: 'published',
    priority: 'high',
    estimatedValue: 4200,
    publishIntent: 'authority',
    hook: 'AI is not replacing developers. It\'s replacing developers who don\'t use AI.',
    primaryCTA: 'Follow for weekly breakdowns',
    repurposeFrom: undefined,
    campaignId: 'camp_001',
    tags: ['AI', 'tech', 'careers', 'developer'],
    notes: 'Best performer of Q1. Repurpose into carousel for LinkedIn.',
    createdBy: 'tm_001',
    assignedTo: 'tm_002',
    approvedBy: 'tm_001',
    approvedAt: '2026-03-01T10:00:00Z',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-03-10T14:22:00Z',
    variants: [
      {
        id: 'cv_001_tiktok',
        platform: 'tiktok',
        platformAccountId: 'acc_tiktok',
        hook: 'POV: your company just hired AI instead of a junior dev 👀',
        caption: 'This is what ACTUALLY happens when companies try to replace engineers with AI... and none of it is what the headlines say. I tracked 3 real companies. Here\'s the data.',
        hashtags: ['#softwareengineering', '#aitools', '#techjobs', '#fyp', '#coding'],
        mentions: [],
        primaryCTA: 'Follow for more real data',
        media: [{ id: 'm_001', type: 'video', url: '/mock/video-ai-dev.mp4', thumbnailUrl: '/mock/thumb-ai-dev.jpg', aspectRatio: '9:16', durationSeconds: 58 }],
        platformSpecific: { duetEnabled: true, stitchEnabled: true, soundId: 'trending_001' },
        status: 'published',
        scheduledAt: '2026-03-05T18:00:00Z',
        publishedAt: '2026-03-05T18:00:12Z',
        metrics: { impressions: 410000, reach: 284000, views: 284000, likes: 18400, comments: 2100, shares: 4300, saves: 3800, watchTimeSeconds: 9744000, completionRate: 61, engagementRate: 7.2, ctr: 3.1, clicks: 8804 },
      },
      {
        id: 'cv_001_youtube',
        platform: 'youtube',
        platformAccountId: 'acc_youtube',
        hook: 'AI is replacing junior developers — but not for the reason you think',
        caption: 'In this video I break down 3 real case studies of companies that tried replacing junior developers with AI tools in 2025. The results might surprise you. Full data, no hype.',
        hashtags: ['#artificialintelligence', '#programming', '#techcareers', '#softwaredevelopment'],
        mentions: [],
        primaryCTA: 'Subscribe for weekly tech breakdowns',
        media: [{ id: 'm_002', type: 'longform', url: '/mock/yt-ai-dev.mp4', thumbnailUrl: '/mock/thumb-yt-ai-dev.jpg', aspectRatio: '16:9', durationSeconds: 724 }],
        platformSpecific: { chapters: ['0:00 Intro', '1:45 Case Study 1', '5:20 Case Study 2', '9:10 Case Study 3', '13:40 What this means for you'], endScreenEnabled: true, tags: ['AI', 'software engineering', 'career advice'], visibility: 'public' },
        status: 'published',
        scheduledAt: '2026-03-06T14:00:00Z',
        publishedAt: '2026-03-06T14:00:08Z',
        metrics: { impressions: 62000, reach: 41000, views: 41000, likes: 2800, comments: 430, shares: 390, saves: 1240, watchTimeSeconds: 18540000, completionRate: 44, engagementRate: 5.9, ctr: 6.8, clicks: 4216 },
      },
      {
        id: 'cv_001_linkedin',
        platform: 'linkedin',
        platformAccountId: 'acc_linkedin',
        hook: 'Hot take: AI isn\'t replacing developers. It\'s raising the floor.',
        caption: 'Three companies tried replacing junior devs with AI this quarter.\n\nHere\'s what actually happened:\n\n→ Company A (200-person SaaS): Hired 0 junior devs, deployed GitHub Copilot + Claude. Senior dev output increased 38%. But production incidents doubled.\n\n→ Company B (50-person startup): Let go of 2 junior engineers. 4 months later rehired 3. The AI couldn\'t own tickets end-to-end.\n\n→ Company C (enterprise): Pilot showed 22% faster feature delivery. But tech debt increased significantly.\n\nThe pattern: AI accelerates execution. It doesn\'t replace judgment.\n\nWhat\'s your read?',
        hashtags: ['#artificialintelligence', '#softwaredevelopment', '#futureofwork', '#techleadership'],
        mentions: [],
        primaryCTA: 'Drop your take in the comments',
        media: [{ id: 'm_003', type: 'image', url: '/mock/li-ai-quote.jpg', aspectRatio: '1:1', altText: 'AI is not replacing developers. It\'s raising the floor.' }],
        platformSpecific: { articleUrl: undefined, targetAudience: 'tech professionals & engineering managers', documentType: 'none', sponsored: false },
        status: 'published',
        publishedAt: '2026-03-06T08:30:00Z',
        metrics: { impressions: 22000, reach: 18400, likes: 1100, comments: 287, shares: 314, saves: 890, engagementRate: 6.3, clicks: 980, ctr: 4.5 },
      },
      {
        id: 'cv_001_x',
        platform: 'x',
        platformAccountId: 'acc_x',
        hook: 'AI is not replacing developers. It\'s replacing developers who don\'t use AI.',
        caption: 'Three companies tried replacing junior devs with AI this quarter. Here\'s what happened 🧵\n\n1/ Company A cut junior hiring entirely. Copilot + Claude for everyone. Senior output up 38%. Production incidents up 2x.',
        hashtags: ['#AI', '#programming', '#dev'],
        mentions: [],
        primaryCTA: 'RT if this matches what you\'re seeing',
        media: [],
        platformSpecific: { isThread: true, threadCount: 8, replySettings: 'everyone' },
        status: 'published',
        publishedAt: '2026-03-05T19:00:00Z',
        metrics: { impressions: 91000, reach: 68000, likes: 3200, comments: 640, shares: 1800, clicks: 2730, ctr: 3.0, engagementRate: 5.5 },
      },
      {
        id: 'cv_001_facebook',
        platform: 'facebook',
        platformAccountId: 'acc_facebook',
        hook: 'Everyone\'s saying AI will replace developers. Here\'s what 3 real companies actually found:',
        caption: 'We analyzed what happened when three tech companies tried replacing junior developers with AI tools this quarter. Spoiler: the results are more nuanced than the headlines.\n\nFull breakdown in the video. Watch time: 58 seconds.',
        hashtags: ['#AI', '#tech', '#careers', '#softwaredevelopment'],
        mentions: [],
        primaryCTA: 'Share with a developer you know',
        media: [{ id: 'm_004', type: 'video', url: '/mock/video-ai-dev.mp4', thumbnailUrl: '/mock/thumb-ai-dev.jpg', aspectRatio: '16:9', durationSeconds: 58 }],
        platformSpecific: { targetingAgeMin: 25, targetingAgeMax: 44, targetingGeo: ['US', 'CA', 'GB'], boostBudget: 0 },
        status: 'published',
        publishedAt: '2026-03-06T12:00:00Z',
        metrics: { impressions: 19800, reach: 14200, views: 9400, likes: 890, comments: 143, shares: 312, clicks: 640, ctr: 3.2, engagementRate: 3.8 },
      },
      {
        id: 'cv_001_threads',
        platform: 'threads',
        platformAccountId: 'acc_threads',
        hook: 'Controversial opinion: AI won\'t replace developers.',
        caption: 'Controversial opinion: AI won\'t replace developers.\n\nIt will replace developers who don\'t use AI.\n\nTracked 3 companies this quarter who tried the replacement playbook. None of it went how they expected. Here\'s the actual data...',
        hashtags: [],
        mentions: [],
        primaryCTA: 'What\'s your read on this?',
        media: [],
        platformSpecific: { crosspostToInstagram: false, replyControl: 'everyone' },
        status: 'published',
        publishedAt: '2026-03-05T20:00:00Z',
        metrics: { impressions: 14200, reach: 11000, likes: 2100, comments: 340, shares: 180, engagementRate: 4.2 },
      },
    ],
  },

  // ─── ci_002 ─── FAILED ──────────────────────────────────────────────────────
  {
    id: 'ci_002',
    title: 'Spring sale — 40% off all plans this week only',
    type: 'image',
    status: 'published',
    priority: 'high',
    estimatedValue: 12000,
    publishIntent: 'promotional',
    hook: 'The biggest sale we\'ve run all year. Ends Friday.',
    primaryCTA: 'Grab 40% off before it\'s gone',
    campaignId: 'camp_002',
    tags: ['sale', 'promotion', 'pricing'],
    notes: 'TikTok rejected for promotional audio. Facebook flagged for misleading claims — needs legal review before retry.',
    createdBy: 'tm_002',
    assignedTo: 'tm_003',
    approvedBy: 'tm_001',
    approvedAt: '2026-03-14T09:00:00Z',
    createdAt: '2026-03-12T10:00:00Z',
    updatedAt: '2026-03-16T11:30:00Z',
    variants: [
      {
        id: 'cv_002_tiktok',
        platform: 'tiktok',
        platformAccountId: 'acc_tiktok',
        hook: '40% off ends FRIDAY — here\'s how to grab it before it\'s gone 🔥',
        caption: 'Our biggest sale of the year is live. 40% off all plans. Only this week. Link in bio to lock it in.',
        hashtags: ['#sale', '#discount', '#saas', '#deal', '#fyp'],
        mentions: [],
        primaryCTA: 'Link in bio',
        media: [{ id: 'm_010', type: 'short', url: '/mock/sale-tiktok.mp4', thumbnailUrl: '/mock/thumb-sale.jpg', aspectRatio: '9:16', durationSeconds: 22 }],
        platformSpecific: { duetEnabled: false, stitchEnabled: false, branded: true },
        status: 'failed',
        scheduledAt: '2026-03-15T09:00:00Z',
        failedReason: 'Rejected by TikTok: promotional content using copyrighted audio without commercial license. Requires re-edit with royalty-free sound.',
        metrics: undefined,
      },
      {
        id: 'cv_002_facebook',
        platform: 'facebook',
        platformAccountId: 'acc_facebook',
        hook: '40% off all plans — this week only.',
        caption: 'Spring sale is live. Get 40% off any plan when you upgrade before Friday midnight. No code needed — discount applies automatically at checkout.',
        hashtags: ['#sale', '#offer', '#saas'],
        mentions: [],
        primaryCTA: 'Claim your 40% off',
        media: [{ id: 'm_011', type: 'image', url: '/mock/sale-fb.jpg', aspectRatio: '1:1', altText: 'Spring sale 40% off all plans' }],
        platformSpecific: { targetingAgeMin: 28, targetingAgeMax: 55, targetingGeo: ['US', 'CA'], boostBudget: 500, callToActionType: 'SHOP_NOW' },
        status: 'failed',
        scheduledAt: '2026-03-15T09:00:00Z',
        failedReason: 'Ad flagged by Facebook policy: "40% off" claims require substantiation documentation. Submitted to appeals — awaiting review.',
        metrics: undefined,
      },
      {
        id: 'cv_002_linkedin',
        platform: 'linkedin',
        platformAccountId: 'acc_linkedin',
        hook: 'We\'re running our biggest discount of the year. Here\'s who it\'s for.',
        caption: 'For teams that have been evaluating us but haven\'t pulled the trigger: this is the week.\n\n40% off all plans, through Friday. No code needed.\n\nIf you\'ve been waiting for the right moment, this is it.',
        hashtags: ['#saas', '#productivity', '#deal'],
        mentions: [],
        primaryCTA: 'See plans and pricing',
        media: [{ id: 'm_012', type: 'image', url: '/mock/sale-li.jpg', aspectRatio: '1:1' }],
        platformSpecific: { documentType: 'none', sponsored: false },
        status: 'published',
        publishedAt: '2026-03-15T08:00:00Z',
        metrics: { impressions: 8400, reach: 6200, likes: 210, comments: 38, shares: 44, clicks: 390, ctr: 4.6, engagementRate: 2.9 },
      },
      {
        id: 'cv_002_x',
        platform: 'x',
        platformAccountId: 'acc_x',
        hook: 'Spring sale. 40% off all plans. Ends Friday.',
        caption: 'Spring sale is live.\n\n40% off all plans through Friday. No code. Discount applies automatically.\n\nLink in bio.',
        hashtags: ['#sale', '#saas'],
        mentions: [],
        primaryCTA: 'Link in bio',
        media: [{ id: 'm_013', type: 'image', url: '/mock/sale-x.jpg', aspectRatio: '16:9' }],
        platformSpecific: { isThread: false, replySettings: 'everyone' },
        status: 'published',
        publishedAt: '2026-03-15T09:30:00Z',
        metrics: { impressions: 11200, reach: 8900, likes: 340, comments: 62, shares: 290, clicks: 880, ctr: 7.9, engagementRate: 3.1 },
      },
    ],
  },

  // ─── ci_003 ─── DRAFT ONLY ─────────────────────────────────────────────────
  {
    id: 'ci_003',
    title: 'Why most content calendars fail (and what to do instead)',
    type: 'carousel',
    status: 'drafting',
    priority: 'medium',
    estimatedValue: 800,
    publishIntent: 'educational',
    hook: 'Your content calendar isn\'t a strategy. It\'s a false sense of control.',
    primaryCTA: 'Save this for your next planning session',
    campaignId: 'camp_001',
    tags: ['content-strategy', 'planning', 'social-media'],
    notes: 'Hook is strong. Captions need a full pass. Hold LinkedIn until carousel design is done. No media assets yet.',
    createdBy: 'tm_003',
    assignedTo: 'tm_002',
    createdAt: '2026-03-20T14:00:00Z',
    updatedAt: '2026-03-22T09:15:00Z',
    variants: [
      {
        id: 'cv_003_linkedin',
        platform: 'linkedin',
        platformAccountId: 'acc_linkedin',
        hook: 'Your content calendar isn\'t a strategy. It\'s a false sense of control.',
        caption: 'Most marketing teams confuse scheduling with strategy.\n\nA full calendar feels productive. But if every post is reactionary, you\'re not building anything — you\'re just staying busy.\n\nHere\'s what actually works: [DRAFT — expand with 5 points]',
        hashtags: ['#contentmarketing', '#contentstrategy', '#marketingtips'],
        mentions: [],
        primaryCTA: 'Save this for your next planning session',
        media: [],
        platformSpecific: { documentType: 'carousel', slideCount: 8, sponsored: false },
        status: 'drafting',
      },
      {
        id: 'cv_003_x',
        platform: 'x',
        platformAccountId: 'acc_x',
        hook: 'Your content calendar isn\'t a strategy.',
        caption: 'Your content calendar isn\'t a strategy.\n\nIt\'s a false sense of control.\n\nHere\'s what separates teams that grow vs teams that just stay busy 🧵\n\n[DRAFT — thread to follow]',
        hashtags: ['#contentmarketing', '#growthhacking'],
        mentions: [],
        primaryCTA: 'Retweet if this hits',
        media: [],
        platformSpecific: { isThread: true, threadCount: 7, replySettings: 'everyone' },
        status: 'drafting',
      },
      {
        id: 'cv_003_tiktok',
        platform: 'tiktok',
        platformAccountId: 'acc_tiktok',
        hook: 'The content calendar is a lie. Here\'s what actually works.',
        caption: '[DRAFT] Hook: calendar ≠ strategy. Walk through the 3 failure modes. End with the framework. Needs voiceover script and b-roll list.',
        hashtags: ['#contentcreator', '#marketingtips', '#fyp'],
        mentions: [],
        primaryCTA: 'Follow for content frameworks',
        media: [],
        platformSpecific: { duetEnabled: false, stitchEnabled: false },
        status: 'drafting',
      },
    ],
  },

  // ─── ci_004 ─── APPROVED / SCHEDULED ───────────────────────────────────────
  {
    id: 'ci_004',
    title: '5 positioning mistakes killing SaaS conversion rates',
    type: 'carousel',
    status: 'approved',
    priority: 'high',
    estimatedValue: 2800,
    publishIntent: 'educational',
    hook: 'Most SaaS landing pages fail before the visitor reads past the headline.',
    primaryCTA: 'Save this for your next homepage audit',
    repurposeFrom: 'ci_001',
    campaignId: 'camp_002',
    tags: ['saas', 'conversion', 'positioning', 'landing-page'],
    notes: 'Repurposed from ci_001 authority angle. LinkedIn + X are priority. TikTok scripted but no shoot date yet.',
    createdBy: 'tm_002',
    assignedTo: 'tm_003',
    approvedBy: 'tm_001',
    approvedAt: '2026-03-25T11:00:00Z',
    createdAt: '2026-03-18T10:00:00Z',
    updatedAt: '2026-03-25T11:05:00Z',
    variants: [
      {
        id: 'cv_004_linkedin',
        platform: 'linkedin',
        platformAccountId: 'acc_linkedin',
        hook: 'Most SaaS landing pages fail before the visitor reads past the headline.',
        caption: '5 positioning mistakes I keep seeing — and what to do instead:\n\n1. Leading with features, not outcomes\n2. Writing for the product, not the buyer\n3. Social proof that proves the wrong thing\n4. A CTA that asks for too much too soon\n5. No visible answer to "why now"\n\nSlide 2 → for each mistake, here\'s the fix.',
        hashtags: ['#saas', '#growthhacking', '#productmarketing', '#conversionoptimization'],
        mentions: [],
        primaryCTA: 'Save this. Share with your PM.',
        media: [{ id: 'm_020', type: 'carousel', url: '/mock/carousel-saas.pdf', thumbnailUrl: '/mock/thumb-carousel-saas.jpg', aspectRatio: '1:1' }],
        platformSpecific: { documentType: 'carousel', slideCount: 10, sponsored: false },
        status: 'scheduled',
        scheduledAt: '2026-04-03T09:00:00Z',
      },
      {
        id: 'cv_004_x',
        platform: 'x',
        platformAccountId: 'acc_x',
        hook: 'Most SaaS landing pages fail before the visitor reads past the headline.',
        caption: '5 positioning mistakes killing SaaS conversion rates 🧵\n\n1/ Leading with features, not outcomes. Visitors don\'t care what your product does. They care what changes for them.',
        hashtags: ['#saas', '#productmarketing'],
        mentions: [],
        primaryCTA: 'Bookmark this thread',
        media: [],
        platformSpecific: { isThread: true, threadCount: 6, replySettings: 'everyone' },
        status: 'approved',
      },
      {
        id: 'cv_004_tiktok',
        platform: 'tiktok',
        platformAccountId: 'acc_tiktok',
        hook: 'Your SaaS homepage is losing sales before anyone reads a word. Here\'s why 👇',
        caption: 'I audited 50 SaaS landing pages and found the same 5 mistakes every time. Here\'s exactly what I\'d fix on each one.',
        hashtags: ['#saas', '#startuplife', '#marketingtips', '#fyp'],
        mentions: [],
        primaryCTA: 'Follow for more SaaS teardowns',
        media: [{ id: 'm_021', type: 'short', url: '/mock/tiktok-saas.mp4', thumbnailUrl: '/mock/thumb-tiktok-saas.jpg', aspectRatio: '9:16', durationSeconds: 52 }],
        platformSpecific: { duetEnabled: false, stitchEnabled: true },
        status: 'approved',
      },
      {
        id: 'cv_004_facebook',
        platform: 'facebook',
        platformAccountId: 'acc_facebook',
        hook: 'Is your SaaS landing page making these 5 mistakes?',
        caption: 'We audited 50 SaaS landing pages this quarter. The same 5 positioning mistakes showed up again and again. Here\'s what they are — and what to do instead.',
        hashtags: ['#saas', '#marketing', '#startup'],
        mentions: [],
        primaryCTA: 'Tag a founder who needs this',
        media: [{ id: 'm_022', type: 'image', url: '/mock/fb-saas.jpg', aspectRatio: '16:9' }],
        platformSpecific: { targetingAgeMin: 28, targetingAgeMax: 50, boostBudget: 150 },
        status: 'review',
      },
    ],
  },

  // ─── ci_005 ─── MIXED STATE: approved on some, blocked on YouTube ──────────
  {
    id: 'ci_005',
    title: 'Behind the build: how we shipped our new analytics dashboard',
    type: 'video',
    status: 'approved',
    priority: 'medium',
    estimatedValue: 1500,
    publishIntent: 'community',
    hook: 'We shipped a full analytics dashboard in 3 weeks. Here\'s what we actually did.',
    primaryCTA: 'Follow to see what we ship next',
    campaignId: 'camp_001',
    tags: ['behind-the-scenes', 'product', 'build-in-public'],
    notes: 'YouTube blocked — waiting on final screen recordings from engineering. All other variants approved and ready.',
    createdBy: 'tm_002',
    assignedTo: 'tm_002',
    approvedBy: 'tm_001',
    approvedAt: '2026-03-27T15:00:00Z',
    createdAt: '2026-03-22T09:00:00Z',
    updatedAt: '2026-03-28T10:00:00Z',
    variants: [
      {
        id: 'cv_005_tiktok',
        platform: 'tiktok',
        platformAccountId: 'acc_tiktok',
        hook: 'We shipped a full analytics dashboard in 3 weeks. Here\'s the honest behind-the-scenes.',
        caption: 'No BS build-in-public. 3 weeks. 1 designer, 2 engineers. Here\'s exactly what we built, what broke, and what we shipped.',
        hashtags: ['#buildinpublic', '#startup', '#productdesign', '#fyp', '#dev'],
        mentions: [],
        primaryCTA: 'Follow to see what we ship next',
        media: [{ id: 'm_030', type: 'short', url: '/mock/tiktok-build.mp4', thumbnailUrl: '/mock/thumb-build.jpg', aspectRatio: '9:16', durationSeconds: 47 }],
        platformSpecific: { duetEnabled: true, stitchEnabled: true },
        status: 'approved',
        scheduledAt: '2026-04-05T17:00:00Z',
      },
      {
        id: 'cv_005_linkedin',
        platform: 'linkedin',
        platformAccountId: 'acc_linkedin',
        hook: 'We shipped a full analytics dashboard in 3 weeks. Here\'s what the process actually looked like.',
        caption: 'Three weeks ago we started from a blank Figma file. Yesterday we shipped.\n\nHere\'s what actually happened in between:\n\nWeek 1: Defined the 5 metrics that matter most to our users. Cut everything else.\nWeek 2: Built the components. Broke them. Rebuilt them.\nWeek 3: Edge cases, edge cases, edge cases. Then shipped.\n\nThe honest part: it was supposed to take 6 weeks. We cut scope ruthlessly.\n\nWhat did we cut? Everything that wasn\'t blocking a key user decision.',
        hashtags: ['#buildinpublic', '#productdevelopment', '#startup', '#saas'],
        mentions: [],
        primaryCTA: 'What would you have cut?',
        media: [{ id: 'm_031', type: 'image', url: '/mock/li-build.jpg', aspectRatio: '1:1' }],
        platformSpecific: { documentType: 'none', sponsored: false },
        status: 'approved',
        scheduledAt: '2026-04-05T08:30:00Z',
      },
      {
        id: 'cv_005_youtube',
        platform: 'youtube',
        platformAccountId: 'acc_youtube',
        hook: 'We shipped a full analytics dashboard in 3 weeks — full behind-the-scenes breakdown',
        caption: 'Full behind-the-scenes of how our team shipped an analytics dashboard in 3 weeks. Design process, engineering decisions, what we cut, what broke, and what we learned.',
        hashtags: ['#buildinpublic', '#startuplife', '#productdevelopment', '#saas'],
        mentions: [],
        primaryCTA: 'Subscribe for more build-in-public content',
        media: [],
        platformSpecific: { chapters: ['0:00 Intro', '1:30 Week 1', '6:00 Week 2', '11:20 Week 3', '16:00 Lessons'], endScreenEnabled: true, visibility: 'public' },
        status: 'blocked',
        blockedReason: 'Waiting on final screen recordings from engineering team. ETA: April 2.',
      },
      {
        id: 'cv_005_threads',
        platform: 'threads',
        platformAccountId: 'acc_threads',
        hook: 'We shipped a full analytics dashboard in 3 weeks.',
        caption: 'We shipped a full analytics dashboard in 3 weeks.\n\nHonest build-in-public breakdown:\n\nWeek 1 — scoped it aggressively. Cut 60% of the original spec.\nWeek 2 — built, broke, rebuilt.\nWeek 3 — edge cases. So many edge cases.\n\nShipped yesterday. Here\'s what I\'d do differently.',
        hashtags: [],
        mentions: [],
        primaryCTA: 'What would you have done differently?',
        media: [],
        platformSpecific: { crosspostToInstagram: false, replyControl: 'everyone' },
        status: 'approved',
        scheduledAt: '2026-04-05T18:00:00Z',
      },
    ],
  },
];
