import { TrendItem } from '@/lib/types';

// 8 trend items covering AI, SaaS, creator economy, productivity.
// Each includes platform-specific angles for all 6 platforms.
// velocity: 'rising' | 'peak' | 'fading'

export const TRENDS: TrendItem[] = [

  {
    id: 'trend_001',
    title: 'AI agents are replacing SaaS dashboards',
    summary: 'A wave of commentary and early product announcements suggests AI agents are beginning to replace traditional SaaS UIs. Users describe tasks rather than clicking through menus. Debate is active on whether this is hype or a genuine platform shift.',
    source: 'Hacker News + X',
    category: 'AI / Product',
    publishedAt: '2026-03-29T08:00:00Z',
    trendScore: 91,
    velocity: 'rising',
    platforms: ['tiktok', 'linkedin', 'x', 'youtube', 'threads'],
    tags: ['AI', 'agents', 'SaaS', 'product', 'UX'],
    platformAngles: {
      tiktok: {
        angle: 'POV: you just described what you wanted and the software did it — no menus, no dashboards',
        contentType: 'short',
        hook: 'The dashboard is dead. AI just killed it.',
        hashtags: ['#aitools', '#saas', '#productivity', '#fyp', '#tech'],
        suggestedCTA: 'Follow to see what gets replaced next',
      },
      linkedin: {
        angle: 'Thought leadership: what the shift from UI to agent means for product teams and B2B buyers',
        contentType: 'article',
        hook: 'The next SaaS company you buy might not have a dashboard at all.',
        hashtags: ['#artificialintelligence', '#productmanagement', '#saas', '#futureofwork'],
        suggestedCTA: 'What does this mean for your product roadmap?',
      },
      x: {
        angle: 'Hot take thread: dashboards as we know them have 3 years left',
        contentType: 'thread',
        hook: 'Dashboards are a UI pattern designed for humans who don\'t have AI. That era is ending.',
        hashtags: ['#AI', '#SaaS', '#productdesign'],
        suggestedCTA: 'Reply with the dashboard you\'d replace first',
      },
      youtube: {
        angle: 'Deep-dive: show real demos of AI agents replacing manual SaaS workflows — side-by-side comparison',
        contentType: 'video',
        hook: 'I replaced 4 SaaS dashboards with AI agents for 30 days. Here\'s what happened.',
        hashtags: ['#AI', '#productivity', '#saas', '#agents'],
        suggestedCTA: 'Subscribe for more real AI workflow tests',
      },
      threads: {
        angle: 'Short take: the design implication — what happens to the UX industry if intent replaces interface',
        contentType: 'text',
        hook: 'If AI agents replace dashboards, what happens to UX designers?',
        hashtags: [],
        suggestedCTA: 'What\'s your take?',
      },
    },
  },

  {
    id: 'trend_002',
    title: 'Creator burnout is becoming a mainstream business story',
    summary: 'Several high-profile creators have publicly stepped back citing burnout. Business press is picking up the mental health and sustainability angle. Audience engagement with burnout content is unusually high across all platforms this month.',
    source: 'Forbes + TikTok commentary',
    category: 'Creator Economy',
    publishedAt: '2026-03-27T10:00:00Z',
    trendScore: 78,
    velocity: 'peak',
    platforms: ['tiktok', 'linkedin', 'threads', 'youtube', 'x'],
    tags: ['creator-economy', 'burnout', 'mental-health', 'content-strategy'],
    platformAngles: {
      tiktok: {
        angle: 'Honest talk: what burnout actually looks like when content is your job — no performance, real experience',
        contentType: 'video',
        hook: 'I almost quit making content last month. Here\'s what was actually happening.',
        hashtags: ['#creatorburnout', '#contentcreator', '#mentalhealth', '#fyp', '#honest'],
        suggestedCTA: 'Follow for the honest version of the creator journey',
      },
      linkedin: {
        angle: 'Business case: sustainable content operations — why the hamster wheel model fails and what replaces it',
        contentType: 'article',
        hook: 'Most content strategies are designed to maximise output. Almost none are designed to last.',
        hashtags: ['#contentmarketing', '#creatoreconomy', '#burnout', '#contentstrategy'],
        suggestedCTA: 'Save this for your next content planning session',
      },
      x: {
        angle: 'Thread: the economics of creator burnout — why the incentive structure almost guarantees it',
        contentType: 'thread',
        hook: 'Creator burnout isn\'t a personal failure. It\'s a predictable outcome of how the incentives are structured.',
        hashtags: ['#creatoreconomy', '#burnout', '#contentcreator'],
        suggestedCTA: 'RT if this describes your experience',
      },
      youtube: {
        angle: 'Long-form: interview format or personal essay — the real cost of building an audience at scale',
        contentType: 'longform',
        hook: 'What no one tells you about building an audience: the more it works, the harder it gets to stop.',
        hashtags: ['#creatorburnout', '#creatoreconomy', '#youtuber', '#contentcreator'],
        suggestedCTA: 'Subscribe — more honest takes on the creator business incoming',
      },
      threads: {
        angle: 'Raw short take: permission-giving post for creators who are running on empty right now',
        contentType: 'text',
        hook: 'It\'s okay to post less. The algorithm will recover. You might not.',
        hashtags: [],
        suggestedCTA: 'How are you actually doing right now?',
      },
    },
  },

  {
    id: 'trend_003',
    title: 'LinkedIn is becoming the new long-form publishing platform',
    summary: 'LinkedIn newsletters and long-form posts are seeing engagement rates significantly above industry averages. Several B2B writers have migrated audiences from Substack to LinkedIn native. Platform is actively promoting article-length content in the feed.',
    source: 'LinkedIn Data + Creator Reports',
    category: 'Platform Shift',
    publishedAt: '2026-03-26T09:00:00Z',
    trendScore: 74,
    velocity: 'rising',
    platforms: ['linkedin', 'x', 'threads'],
    tags: ['linkedin', 'longform', 'newsletter', 'B2B', 'publishing'],
    platformAngles: {
      linkedin: {
        angle: 'Meta angle: write a long-form post about writing long-form posts on LinkedIn — proven engagement loop',
        contentType: 'article',
        hook: 'I\'ve been publishing long-form on LinkedIn for 6 months. Here\'s exactly what the data shows.',
        hashtags: ['#linkedin', '#contentcreator', '#b2bmarketing', '#thoughtleadership'],
        suggestedCTA: 'Follow for weekly data from my LinkedIn experiment',
      },
      x: {
        angle: 'Contrarian: X thread arguing LinkedIn is eating Substack\'s lunch for B2B writers',
        contentType: 'thread',
        hook: 'Substack is great. LinkedIn might be better for B2B writers right now. Here\'s the data.',
        hashtags: ['#linkedin', '#substack', '#newsletter', '#contentmarketing'],
        suggestedCTA: 'Where are you building your audience in 2026?',
      },
      threads: {
        angle: 'Short take: platform recommendation for B2B creators considering where to invest time',
        contentType: 'text',
        hook: 'If you write for a B2B audience and you\'re not on LinkedIn yet: the window is open right now.',
        hashtags: [],
        suggestedCTA: 'What platform is working best for you?',
      },
    },
  },

  {
    id: 'trend_004',
    title: 'Short-form video attention spans are getting shorter — data confirms',
    summary: 'New platform data suggests optimal TikTok and Reels length has dropped below 30 seconds for maximum completion rate. Creators reporting that 15-second formats now outperform 60-second consistently. Debate around whether depth is being permanently sacrificed.',
    source: 'TikTok Creator Insights + Sprout Social',
    category: 'Content Strategy',
    publishedAt: '2026-03-25T14:00:00Z',
    trendScore: 82,
    velocity: 'peak',
    platforms: ['tiktok', 'youtube', 'linkedin', 'x'],
    tags: ['short-form', 'attention', 'tiktok', 'video-strategy', 'reels'],
    platformAngles: {
      tiktok: {
        angle: 'Meta content: a 15-second video about why 15-second videos now outperform 60-second videos',
        contentType: 'short',
        hook: 'The optimal TikTok length just dropped again. Here\'s the new number.',
        hashtags: ['#tiktokstrategy', '#contentcreator', '#shortform', '#fyp', '#algorithm'],
        suggestedCTA: 'Follow for weekly platform data',
      },
      youtube: {
        angle: 'Data-backed deep dive: Shorts vs long-form — is short-form cannibalising your main channel?',
        contentType: 'video',
        hook: 'Shorts are getting more views. Long-form is making more money. Here\'s how to run both.',
        hashtags: ['#youtubeshorts', '#youtubestrategy', '#contentcreator', '#youtubealgoritm'],
        suggestedCTA: 'Subscribe — full YouTube strategy breakdown next week',
      },
      linkedin: {
        angle: 'B2B take: attention economics and what shrinking attention spans mean for enterprise content strategy',
        contentType: 'article',
        hook: 'Attention spans aren\'t shrinking. Competition for them is intensifying. There\'s a difference.',
        hashtags: ['#contentmarketing', '#b2bmarketing', '#videocontent', '#attention'],
        suggestedCTA: 'Save this for your next content strategy review',
      },
      x: {
        angle: 'Hot take: the race to shorter content is a race to the bottom — and there\'s no floor',
        contentType: 'thread',
        hook: '15 seconds used to be a TikTok. Now it\'s aspirational. We need to talk about what we\'re optimising for.',
        hashtags: ['#contentcreator', '#shortform', '#attention', '#media'],
        suggestedCTA: 'What\'s the shortest content format you\'d actually invest in?',
      },
    },
  },

  {
    id: 'trend_005',
    title: 'Micro-SaaS is having a moment — solo founders shipping in weeks',
    summary: 'AI coding tools have dramatically lowered the barrier to ship SaaS products. A wave of solo founders are building and launching micro-SaaS tools in days to weeks. Revenue reports on X and Indie Hackers are driving significant engagement and inspiration content.',
    source: 'Indie Hackers + X',
    category: 'SaaS / Entrepreneurship',
    publishedAt: '2026-03-24T11:00:00Z',
    trendScore: 86,
    velocity: 'rising',
    platforms: ['x', 'tiktok', 'linkedin', 'youtube', 'threads'],
    tags: ['micro-saas', 'indie-hackers', 'solo-founder', 'AI', 'build-in-public'],
    platformAngles: {
      x: {
        angle: 'Build-in-public thread: document the process of shipping a micro-SaaS from idea to first dollar',
        contentType: 'thread',
        hook: 'I\'m shipping a micro-SaaS this week. Following along in real time.',
        hashtags: ['#microsaas', '#buildinpublic', '#indiehackers', '#solofounder'],
        suggestedCTA: 'Follow for daily updates',
      },
      tiktok: {
        angle: 'Storytime format: "I built a SaaS in a weekend and it made money" — first-person narrative',
        contentType: 'short',
        hook: 'I built a SaaS product this weekend. It made money before Monday.',
        hashtags: ['#microsaas', '#solofounder', '#buildinpublic', '#fyp', '#startup'],
        suggestedCTA: 'Follow to see what I ship next',
      },
      linkedin: {
        angle: 'Thought leadership: what micro-SaaS tells us about the future of software entrepreneurship',
        contentType: 'article',
        hook: 'The barrier to building a software business just dropped by 90%. Here\'s what that actually means.',
        hashtags: ['#saas', '#entrepreneurship', '#AI', '#solofounder', '#startup'],
        suggestedCTA: 'What micro-SaaS would you build if you could ship in a week?',
      },
      youtube: {
        angle: 'Full build video: ship a real micro-SaaS live on camera from idea to launch',
        contentType: 'longform',
        hook: 'Building a SaaS product live on camera. No cuts. Real mistakes. Here\'s what happened.',
        hashtags: ['#microsaas', '#buildinpublic', '#programming', '#startup', '#solofounder'],
        suggestedCTA: 'Subscribe — shipping another one next month',
      },
      threads: {
        angle: 'Short observation: why micro-SaaS is the most honest form of product validation',
        contentType: 'text',
        hook: 'Micro-SaaS isn\'t just a business model. It\'s the fastest way to know if an idea is real.',
        hashtags: [],
        suggestedCTA: 'What would you build?',
      },
    },
  },

  {
    id: 'trend_006',
    title: 'X algorithm changes are tanking organic reach for text posts',
    summary: 'Multiple prominent accounts reporting significant drops in organic impressions on text-only posts in the past 3 weeks. Speculation that X is deprioritising text in favour of video and images. Engagement on threads down 20–40% for many creators.',
    source: 'X creator reports + Social Media Today',
    category: 'Platform Algorithm',
    publishedAt: '2026-03-28T07:00:00Z',
    trendScore: 88,
    velocity: 'rising',
    platforms: ['x', 'linkedin', 'threads', 'tiktok'],
    tags: ['X', 'algorithm', 'organic-reach', 'platform-changes', 'social-media'],
    platformAngles: {
      x: {
        angle: 'Direct commentary with data: share your own impressions drop and ask audience if they\'re seeing the same',
        contentType: 'text',
        hook: 'My X impressions dropped 34% in 3 weeks with no change in posting cadence. Anyone else seeing this?',
        hashtags: ['#xalgorithm', '#organicreach', '#socialmedia'],
        suggestedCTA: 'Reply with your numbers — building a picture of scale',
      },
      linkedin: {
        angle: 'Platform diversification argument: why X reach drops are an argument for owning your audience',
        contentType: 'article',
        hook: 'X just reminded everyone why you can\'t rent your audience from a platform.',
        hashtags: ['#socialmedia', '#contentmarketing', '#audiencebuilding', '#digitalstrategy'],
        suggestedCTA: 'What\'s your platform diversification strategy?',
      },
      threads: {
        angle: 'Migration opportunity: reach out to X users who are frustrated and make the case for Threads',
        contentType: 'text',
        hook: 'If X is tanking your reach, this is your sign to try Threads.',
        hashtags: [],
        suggestedCTA: 'Drop your handle — let\'s connect here instead',
      },
      tiktok: {
        angle: 'Explainer video: what the X algorithm change means for creators and where to invest instead',
        contentType: 'short',
        hook: 'X just killed organic reach for text posts. Here\'s where smart creators are going instead.',
        hashtags: ['#socialmediatips', '#algorithm', '#contentcreator', '#fyp', '#xtwitter'],
        suggestedCTA: 'Follow for platform strategy breakdowns',
      },
    },
  },

  {
    id: 'trend_007',
    title: 'Faceless YouTube channels hitting 100K+ subs — the AI voiceover wave',
    summary: 'A growing number of YouTube channels using AI voiceovers and stock footage are hitting 100K+ subscribers. Several channels launched in under 6 months. Controversy over whether this is a sustainable strategy or a temporary arbitrage about to be closed by the platform.',
    source: 'YouTube creator forums + Niche Pursuits',
    category: 'Creator Economy / AI',
    publishedAt: '2026-03-23T12:00:00Z',
    trendScore: 71,
    velocity: 'fading',
    platforms: ['youtube', 'tiktok', 'x'],
    tags: ['youtube', 'faceless', 'AI-voiceover', 'passive-income', 'creator'],
    platformAngles: {
      youtube: {
        angle: 'Honest review: test a faceless AI channel for 30 days and report the real numbers',
        contentType: 'video',
        hook: 'I ran a faceless AI YouTube channel for 30 days. Here\'s exactly what happened.',
        hashtags: ['#facelessyoutube', '#aivoiceover', '#youtubestrategy', '#passiveincome'],
        suggestedCTA: 'Subscribe — full data breakdown in the next video',
      },
      tiktok: {
        angle: 'Fast take: is faceless YouTube a real business or an arbitrage window closing fast?',
        contentType: 'short',
        hook: 'Everyone\'s starting faceless YouTube channels. Here\'s the honest timeline for how long this works.',
        hashtags: ['#facelessyoutube', '#youtube', '#contentcreator', '#fyp', '#passiveincome'],
        suggestedCTA: 'Follow for the honest content strategy takes',
      },
      x: {
        angle: 'Thread: the economics of faceless channels — what the revenue actually looks like vs the claim',
        contentType: 'thread',
        hook: 'People are making $10K/month from faceless YouTube. Here\'s what they\'re not showing you.',
        hashtags: ['#youtube', '#passiveincome', '#faceless', '#AI'],
        suggestedCTA: 'RT if you\'ve looked into this',
      },
    },
  },

  {
    id: 'trend_008',
    title: 'B2B brands are finally winning on TikTok',
    summary: 'Several traditionally stiff B2B brands have posted TikToks with 1M+ views by leaning into humour, self-awareness, and behind-the-scenes content. The success cases are generating significant press and inspiring other B2B marketers to experiment.',
    source: 'Marketing Week + TikTok Business Blog',
    category: 'B2B Marketing / TikTok',
    publishedAt: '2026-03-26T15:00:00Z',
    trendScore: 77,
    velocity: 'rising',
    platforms: ['tiktok', 'linkedin', 'x', 'threads'],
    tags: ['B2B', 'tiktok', 'brand-marketing', 'humour', 'short-form'],
    platformAngles: {
      tiktok: {
        angle: 'B2B brand doing something unexpectedly funny or self-aware — lean into the absurdity of the space',
        contentType: 'short',
        hook: 'B2B software company does TikTok. Here\'s why it actually worked.',
        hashtags: ['#b2bmarketing', '#tiktokforbusiness', '#brandmarketing', '#fyp', '#marketing'],
        suggestedCTA: 'Follow to see our B2B TikTok experiment play out live',
      },
      linkedin: {
        angle: 'Case study: what B2B brands getting TikTok right are actually doing — and what the holdouts are missing',
        contentType: 'carousel',
        hook: '3 B2B brands went viral on TikTok this month. Here\'s exactly what they did differently.',
        hashtags: ['#b2bmarketing', '#tiktok', '#contentmarketing', '#brandstrategy'],
        suggestedCTA: 'Save this for your next marketing team meeting',
      },
      x: {
        angle: 'Hot take: the B2B brands winning on TikTok are winning because they stopped being B2B brands on TikTok',
        contentType: 'thread',
        hook: 'The B2B brands killing it on TikTok have one thing in common: they don\'t sound like B2B brands.',
        hashtags: ['#b2bmarketing', '#tiktok', '#branding'],
        suggestedCTA: 'Which B2B brand surprised you most on TikTok?',
      },
      threads: {
        angle: 'Observation: give marketers permission to try unexpected formats — short encouraging take',
        contentType: 'text',
        hook: 'Your B2B audience is also on TikTok at 11pm watching funny videos. You\'re allowed to meet them there.',
        hashtags: [],
        suggestedCTA: 'Which brand do you think would crush it on TikTok?',
      },
    },
  },
];
